/**
 * @author Benjamin Berman
 * Derived from Cards Against Humanity
 * Creative Commons NC-BY-SA 2.0
 *
 * This derived work, cards.js, is also licensed
 * Creative Commons NC-BY-SA 2.0
 */

var CAH_QUESTION_CARDS;
CAH_QUESTION_CARDS = ["A romantic, candlelit dinner would be incomplete without __.",
    "After the earthquake, Sean Penn brought __ to the people of Haiti.",
    "Alternative medicine is now embracing the curative powers of __.",

    "Anthropologists have recently discovered a primitive tribe that worships __.",
    "BILLY MAYS HERE FOR __.",
    "Betcha can't have just one!",
    "But before I kill you, Mr. Bond, I must show you __.",
    "Coming to Broadway this season, __: The Musical.",
    "Daddy, why is Mommy crying?",
    "Dear Abby, I'm having some trouble with __ and would like your advice.",
    "Due to a PR fiasco, Wal*Mart no longer offers __.",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __.",
    "During sex, I like to think about __.",

    "How am I maintaining my relationship status?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __.",
    "I drink to forget __.",
    "I got 99 problems but __ ain't one.",

    "I wish I hadn't lost the instruction manual for __.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __.",
    "In 1000 years, when paper money is but a distant memory, __ will be our currency.",
    "In L.A. County Jail, word is you can trade 200 cigarettes for __.",

    "In Michael Jackson's final moments, he thought about __.",

    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __ for the first time.",
    "Instead of coal, Santa now gives the bad children __.",
    "It's a pity that kids these days are all getting involved with __.",
    "It's a trap!",
    "Life for American Indians was forever changed when the White Man introduced them to __.",
    "Life was difficult for cavemen before __.",

    "MTV's new reality show features eight washed-up celebrities living with __.",
    "Major League Baseball has banned __ for giving players an unfair advantage.",

    "Maybe she's born with it. Maybe it's __.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __.",
    "Next on ESPN2, the World Series of __.",

    "Sorry everyone, I just __ .",

    "Studies show that lab rats navigate mazes 50% faster after being exposed to __.",
    "TSA guidelines now prohibit __ on airplanes.",

    "The class field trip was completely ruined by __.",
    "This is the way the world ends, This is the way the world ends, Not with a bang but with __.",
    "War! What is it good for?",
    "What am I giving up for Lent?",
    "What are my parents hiding from me?",
    "What did I bring back from Mexico?",
    "What did Vin Diesel eat for dinner?",
    "What did the U.S. airdrop to the children of Afghanistan?",
    "What do old people smell like?",
    "What does Dick Cheney prefer?",
    "What don't you want to find in your Chinese food?",
    "What ended my last relationship?",
    "What gets better with age?",
    "What gives me uncontrollable gas?",
    "What helps Obama unwind?",
    "What is Batman's guilty pleasure?",
    "What never fails to liven up the party?",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "What will always get you laid?",
    "What would grandma find disturbing, yet oddly charming?",
    "What's Teach for America using to inspire inner city students to succeed?",
    "What's the new fad diet?",
    "What's a girl's best friend?",
    "What's my anti-drug?",
    "What's my secret power?",
    "What's that smell?",
    "What's that sound?",
    "What's the crustiest?",
    "What's the most emo?",
    "What's the next Happy Meal® toy?",

    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __.",

    "When I'm in prison, I'll have __ smuggled in.",
    "When Pharaoh remained unmoved, Moses called down a Plague of __.",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __.",
    "White people like __ .",
    "Who stole the cookies from the cookie jar?",
    "Why am I sticky?",
    "Why can't I sleep at night?",
    "Why do I hurt all over?",

    "__: good to the last drop.",

    "__. High five, bro.",
    "__. That's how I want to die.",
    "__: kid tested, mother approved.",
    "__? There's an app for that.",
    "He who controls __ controls the world.",
    "The CIA now interrogates enemy agents by repeatedly subjecting them to __.",

    "In Rome, there are whisperings that the Vatican has a secret room devoted to __.",
    "Science will never explain the origin of __.",
    "When all else fails, I can always masturbate to __.",
    "I learned the hard way that you can't cheer up a grieving friend with __.",
    "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __.",

    "The socialist governments of Scandinavia have declared that access to __ is a basic human right.",
    "In his new self-produced album, Kanye West raps over the sounds of __.",
    "What's the gift that keeps on giving?",
    "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __ and his wits.",
    "When I pooped, what came out of my butt?",
    "In the distant future, historians will agree that __ marked the beginning of America's decline.",

    "What has been making life difficult at the nudist colony?",

    "And I would have gotten away with it, too, if it hadn't been for __!",
    "What brought the orgy to a grinding halt?",

    "During his midlife crisis, my dad got really into __.",

    "My new favorite porn star is Joey &quot;__&quot; McGee.",
    "Before I run for president, I must destroy all evidence of my involvement with __.",
    "This is your captain speaking. Fasten your seat belts and prepare for __.",
    "In his newest and most difficult stunt, David Blaine must escape from __.",
    "The Five Stages of Grief: denial, anger, bargaining, __, acceptance.",


    "Members of New York's social elite are paying thousands of dollars just to experience __.",
    "This month's Cosmo: &quot;Spice up your sex life by bringing __ into the bedroom.&quot;",
    "Little Miss Muffet / Sat on a tuffet / Eating her curds and __.",

    "My country, 'tis of thee, sweet land of __.",
    "After months of debate, the Occupy Wall Street General Assembly could only agree on &quot;More __!&quot;",

    "Next time on Dr. Phil: How to talk to your child about __.",
    "Only two things in life are certain: death and __.",
    "Everyone down on the ground! We don't want to hurt anyone. We're just here for __.",
    "The healing process began when I joined a support group for victims of __.",
    "The votes are in, and the new high school mascot is __.",
    "Charades was ruined for me forever when my mom had to act out __.",

    "Tonight on 20/20: What you don't know about __ could kill you."];

var CAH_ANSWER_CARDS;
CAH_ANSWER_CARDS = ["(I am doing kegels right now).",
    "2 Girls 1 Cup.",
    "72 virgins.",
    "8 oz. of sweet Mexican black-tar heroin.",
    "A bag of magic beans.",
    "A balanced breakfast.",
    "A beached whale.",
    "A big black dick.",
    "A big hoopla about nothing.",
    "A bleached asshole.",
    "A bloody pacifier.",
    "A Bop It.",
    "A brain tumor.",
    "A can of whoop-ass.",
    "A cartoon camel enjoying the smooth, refreshing taste of a cigarette.",
    "A clandestine butt scratch.",
    "A cooler full of organs.",
    "A crappy little hand.",
    "A death ray.",
    "A defective condom.",
    "A disappointing birthday party.",
    "A drive-by shooting.",
    "A falcon with a cap on its head.",
    "A fetus.",
    "A foul mouth.",
    "A gassy antelope.",
    "A gentle caress of the inner thigh.",
    "A good sniff.",
    "A grande sugar-free iced soy caramel macchiato.",
    "A Gypsy curse.",
    "A homoerotic volleyball montage.",
    "A hot mess.",
    "A LAN party.",
    "A lifetime of sadness.",
    "A look-see.",
    "A low standard of living.",
    "A mating display.",
    "A micropenis.",
    "A middle-aged man on roller skates.",
    "A mime having a stroke.",
    "A moment of silence.",
    "A monkey smoking a cigar.",
    "A mopey zoo lion.",
    "A murder most foul.",
    "A neglected Tamagotchi™.",
    "A nuanced critique.",
    "A passionate Latino lover.",
    "A really cool hat.",
    "A rival dojo.",
    "A robust mongoloid.",
    "A sad handjob.",
    "A salty surprise.",
    "A sassy black woman.",
    "A sausage festival.",
    "A sea of troubles.",
    "A snapping turtle biting the tip of your penis.",
    "A stray pube.",
    "A Super Soaker™ full of cat pee.",
    "A thermonuclear detonation.",
    "A time travel paradox.",
    "A tiny horse.",
    "A web of lies.",
    "A wheelchair death race.",
    "A windmill full of corpses.",
    "A wisecracking terrorist.",
    "A woman scorned.",
    "A zesty breakfast burrito.",
    "Aaron Burr.",
    "Abstinence.",
    "Active listening.",
    "Actually taking candy from a baby.",
    "Adderall™.",
    "Adult Friend Finder.",
    "Agriculture.",
    "AIDS.",
    "Alcoholism.",
    "All-you-can-eat shrimp for $4.99.",
    "Altar boys.",
    "America.",
    "American Gladiators.",
    "Amputees.",
    "An asymmetric boob job.",
    "An erection that lasts longer than four hours.",
    "An honest cop with nothing left to lose.",
    "An ice-pick lobotomy.",
    "An M. Night Shyamalan plot twist.",
    "An Oedipus complex.",
    "Anal beads.",
    "Another god-damn vampire movie.",
    "Apologizing.",
    "Appreciative snapping.",
    "Arnold Schwarzenegger.",
    "Asians who aren't good at math.",
    "Assless chaps.",
    "Attitude.",
    "Auschwitz.",
    "Authentic Mexican cuisine.",
    "Autocannibalism.",
    "Axe Body Spray.",
    "Balls.",
    "Bananas in Pajamas.",
    "Barack Obama.",
    "BATMAN!!!",
    "Beating your wives.",
    "Bees?",
    "Being a busy adult with many important things to do.",
    "Being a dick to children.",
    "Being a dinosaur.",
    "Being a motherfucking sorcerer.",
    "Being fabulous.",
    "Being marginalized.",
    "Being on fire.",
    "Being rich.",
    "Bestiality.",
    "Bill Nye the Science Guy.",
    "Bingeing and purging.",
    "Bitches.",
    "Black people.",
    "Bling.",
    "Bond, James Bond.",
    "Bono.",
    "Booby-trapping the house to foil burglars.",
    "Boogers.",
    "Bosnian chicken farmers.",
    "Breaking out into song and dance.",
    "Britney Spears at 55.",
    "Canned tuna with extra dolphin.",
    "Cards Against Humanity.",
    "Carnies.",
    "Catapults.",
    "Centaurs.",
    "Chainsaws for hands.",
    "Charisma.",
    "Cheating in the Special Olympics.",
    "Child abuse.",
    "Child beauty pageants.",
    "Children on leashes.",
    "Chivalry.",
    "Christopher Walken.",
    "Chutzpah.",
    "Civilian casualties.",
    "Clams.",
    "Classist undertones.",
    "Coat hanger abortions.",
    "Cockfights.",
    "College.",
    "Concealing a boner.",
    "Consultants.",
    "Copping a feel.",
    "Coughing into a vagina.",
    "Count Chocula.",
    "Creed.",
    "Crippling debt.",
    "Crumpets with the Queen.",
    "Crystal meth.",
    "Cuddling.",
    "Customer service representatives.",
    "Cybernetic enhancements.",
    "Daddy issues.",
    "Dance of the Sugar Plum Fairies.",
    "Dancing with a broom.",
    "Darth Vader.",
    "Date rape.",
    "Dave Matthews Band.",
    "Dead babies.",
    "Dead parents.",
    "Deflowering a princess.",
    "Dental dams.",
    "Dick Cheney.",
    "Dick fingers.",
    "Doin' it in the butt.",
    "Doing the right thing.",
    "Domino's™ Oreo™ Dessert Pizza.",
    "Dorito breath.",
    "Douchebags on their iPhones.",
    "Drinking alone.",
    "Dropping a chandelier on your enemies and riding the rope up.",
    "Drum circles.",
    "Dry heaving.",
    "Dwarf tossing.",
    "Dying of dysentery.",
    "Dying.",
    "Eastern European Turbo-Folk music.",
    "Eating all of the cookies before the AIDS bake-sale.",
    "Eating an albino.",
    "Eating the last known bison.",
    "Eating too much of a lamp.",
    "Edible underpants.",
    "Elderly Japanese men.",
    "Embryonic stem cells.",
    "Emotions.",
    "Enormous Scandinavian women.",
    "Erectile dysfunction.",
    "Estrogen.",
    "Ethnic cleansing.",
    "Eugenics.",
    "Euphoria™ by Calvin Klein.",
    "Exactly what you'd expect.",
    "Exchanging pleasantries.",
    "Existentialists.",
    "Expecting a burp and vomiting on the floor.",
    "Explosions.",
    "Fabricating statistics.",
    "Faith healing.",
    "Famine.",
    "Fancy Feast®.",
    "Farting and walking away.",
    "Fear itself.",
    "Feeding Rosie O'Donnell.",
    "Fiery poops.",
    "Figgy pudding.",
    "Finding a skeleton.",
    "Finger painting.",
    "Fingering.",
    "Firing a rifle into the air while balls deep in a squealing hog.",
    "Five-Dollar Footlongs™.",
    "Flash flooding.",
    "Flavored condoms.",
    "Flesh-eating bacteria.",
    "Flightless birds.",
    "Flying sex snakes.",
    "Foreskin.",
    "Forgetting the Alamo.",
    "Former President George W. Bush.",
    "Four Loko.",
    "Free samples.",
    "Friction.",
    "Friendly fire.",
    "Friends who eat all the snacks.",
    "Friends with benefits.",
    "Frolicking.",
    "Front butt.",
    "Full frontal nudity.",
    "Gandalf.",
    "Gandhi.",
    "Gary Coleman.",
    "Geese.",
    "Genetically engineered super-soldiers.",
    "Genghis Khan.",
    "Genital piercings.",
    "George Clooney's musk.",
    "German dungeon porn.",
    "Getting abducted by Peter Pan.",
    "Getting drunk on mouthwash.",
    "Getting in her pants, politely.",
    "Getting naked and watching Nickelodeon.",
    "Getting really high.",
    "Getting so angry that you pop a boner.",
    "Ghosts.",
    "Girls who shouldn't go wild.",
    "Giving 110%.",
    "Gladiatorial combat.",
    "Glenn Beck being harried by a swarm of buzzards.",
    "Glenn Beck catching his scrotum on a curtain hook.",
    "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.",
    "Glenn Beck.",
    "Global Warming.",
    "Gloryholes.",
    "Go-Gurt®.",
    "Goats eating cans.",
    "Goblins.",
    "God.",
    "Golden showers.",
    "Good grammar.",
    "Grandma.",
    "Grave robbing.",
    "Guys who don't call.",
    "Half-assed foreplay.",
    "Harry Potter erotica.",
    "Have some more kugel.",
    "Heartwarming orphans.",
    "Heath Ledger.",
    "Her Royal Highness, Queen Elizabeth II.",
    "Heteronormativity.",
    "Hipsters.",
    "Historical revisionism.",
    "Historically black colleges.",
    "Home video of Oprah sobbing into a Lean Cuisine®.",
    "Homeless people.",
    "Hope.",
    "Hormone injections.",
    "Horrifying laser hair removal accidents.",
    "Horse meat.",
    "Hot cheese.",
    "Hot people.",
    "Hot Pockets®.",
    "Hulk Hogan.",
    "Hunting accidents.",
    "Hurricane Katrina.",
    "I'm friends with your dad on Facebook™.",
    "Impotence.",
    "Improvised explosive devices.",
    "Inappropriate yodeling.",
    "Incest.",
    "Insatiable blood lust.",
    "Intelligent Design.",
    "Irritable Bowel Syndrome.",
    "Italians.",
    "Jafar.",
    "Jean-Claude Van Damme.",
    "Jerking off into a pool of children's tears.",
    "Jew-fros.",
    "Jewish fraternities.",
    "Jibber-jabber.",
    "John Wilkes Booth.",
    "Judge Judy.",
    "Just the tip.",
    "Justin Bieber.",
    "Kamikaze pilots.",
    "Kanye West.",
    "Keanu Reeves.",
    "Keeping Christ in Christmas.",
    "Keg stands.",
    "Kibbles ‘n Bits™.",
    "Kids with ass cancer.",
    "Kim Jong-il.",
    "Lactation.",
    "Lady Gaga.",
    "Lance Armstrong's missing testicle.",
    "Land mines.",
    "Laying an egg.",
    "Leaving an awkward voicemail.",
    "Leprosy.",
    "Leveling up.",
    "Licking things to claim them as your own.",
    "Literally eating shit.",
    "Lockjaw.",
    "Loose lips.",
    "Lumberjack fantasies.",
    "Lunchables™.",
    "Mad Cow Disease.",
    "Mad hacky-sack skills.",
    "Making a pouty face.",
    "Making sex at her.",
    "Making the penises kiss.",
    "Man meat.",
    "Martha Stewart.",
    "Masturbation.",
    "Mathletes.",
    "Me time.",
    "MechaHitler.",
    "Media coverage.",
    "Medieval Times® Dinner &amp; Tournament.",
    "Men.",
    "Menstruation.",
    "Michael Jackson.",
    "Michelle Obama's arms.",
    "Moral ambiguity.",
    "Morgan Freeman's voice.",
    "Mouth herpes.",
    "Mr. Clean, right behind you.",
    "Muhammad (Praise Be Unto Him).",
    "Multiple stab wounds.",
    "Mutually-assured destruction.",
    "Muzzy.",
    "My collection of high-tech sex toys.",
    "My genitals.",
    "My humps.",
    "My inner demons.",
    "My machete.",
    "My relationship status.",
    "My sex life.",
    "My soul.",
    "My vagina.",
    "Natalie Portman.",
    "Natural male enhancement.",
    "Natural selection.",
    "Nazis.",
    "Necrophilia.",
    "Neil Patrick Harris.",
    "New Age music.",
    "Nickelback.",
    "Nicolas Cage.",
    "Nip slips.",
    "Nipple blades.",
    "Nocturnal emissions.",
    "Not giving a shit about the Third World.",
    "Not reciprocating oral sex.",
    "Nubile slave boys.",
    "Obesity.",
    "Object permanence.",
    "Old-people smell.",
    "Ominous background music.",
    "One thousand Slim Jims.",
    "Oompa-Loompas.",
    "Opposable thumbs.",
    "Overcompensation.",
    "Overpowering your father.",
    "Oversized lollipops.",
    "Pabst Blue Ribbon.",
    "Pac-Man uncontrollably guzzling cum.",
    "Panda sex.",
    "Panty raids.",
    "Paris Hilton.",
    "Parting the Red Sea.",
    "Party poopers.",
    "Passable transvestites.",
    "Passing a kidney stone.",
    "Passive-aggressive Post-it notes.",
    "PCP.",
    "Peanut Butter Jelly Time.",
    "Pedophiles.",
    "Peeing a little bit.",
    "Penis envy.",
    "People who smell their own socks.",
    "Picking up girls at the abortion clinic.",
    "Pictures of boobs.",
    "Pistol-whipping a hostage.",
    "Pixelated bukkake.",
    "Police brutality.",
    "Pooping back and forth. Forever.",
    "Pooping in the soup.",
    "Poor life choices.",
    "Poor people.",
    "Poorly-timed Holocaust jokes.",
    "Popped collars.",
    "Porn stars.",
    "Powerful thighs.",
    "Prancing.",
    "Praying the gay away.",
    "Preteens.",
    "Pretending to care.",
    "Pterodactyl eggs.",
    "Puberty.",
    "Public ridicule.",
    "Pulling out.",
    "Puppies!",
    "Queefing.",
    "Quiche.",
    "Quivering jowls.",
    "Racially-biased SAT questions.",
    "Racism.",
    "Raping and pillaging.",
    "Raptor attacks.",
    "Re-gifting.",
    "Repression.",
    "Republicans.",
    "Revenge fucking.",
    "Riding off into the sunset.",
    "Ring Pops™.",
    "Rip Torn drop-kicking anti-Semitic lesbians.",
    "Ripping into a man's chest and pulling out his still-beating heart.",
    "Road head.",
    "Robbing a sperm bank.",
    "Robert Downey, Jr.",
    "RoboCop.",
    "Ronald Reagan.",
    "Roofies.",
    "Ryan Gosling riding in on a white horse.",
    "Same-sex ice dancing.",
    "Santa Claus.",
    "Sarah Palin.",
    "Saxophone solos.",
    "Scalping.",
    "Science.",
    "Scientology.",
    "Scrotum tickling.",
    "Scrubbing under the folds.",
    "Sean Connery.",
    "Sean Penn.",
    "Seduction.",
    "Self-loathing.",
    "Seppuku.",
    "Serfdom.",
    "Sexting.",
    "Sexual humiliation.",
    "Sexual tension.",
    "Sexy pillow fights.",
    "Sexy Siamese twins.",
    "Shaft.",
    "Shapeshifters.",
    "Shaquille O'Neal's acting career.",
    "Sharing needles.",
    "Shorties and blunts.",
    "Showing up to an orgy for the food.",
    "Sipping artificial popcorn butter.",
    "Skeletor.",
    "Slow motion.",
    "Smallpox blankets.",
    "Smegma.",
    "Sniffing glue.",
    "Soiling oneself.",
    "Soup that is too hot.",
    "Space muffins.",
    "Spectacular abs.",
    "Sperm whales.",
    "Spontaneous human combustion.",
    "Statistically validated stereotypes.",
    "Stephen Hawking talking dirty.",
    "Steve Irwin.",
    "Stifling a giggle at the mention of Hutus and Tutsis.",
    "Stranger danger.",
    "Substitute teachers.",
    "Sucking some dicks to not get drafted.",
    "Sudden Poop Explosion Disease.",
    "Suicidal thoughts.",
    "Sunshine and rainbows.",
    "Surprise sex!",
    "Sweet, sweet vengeance.",
    "Switching to Geico®.",
    "Swooping.",
    "Take-backsies.",
    "Taking off your shirt.",
    "Tangled Slinkys.",
    "Tasteful sideboob.",
    "Teaching a robot to love.",
    "Team-building exercises.",
    "Teenage pregnancy.",
    "Tentacle porn.",
    "Testicular torsion.",
    "That one gay Teletubby.",
    "That thing that electrocutes your abs.",
    "The American Dream.",
    "The Amish.",
    "The Big Bang.",
    "The blood of Christ.",
    "The boners of the elderly.",
    "The Care Bear Stare.",
    "The Chinese gymnastics team.",
    "The chronic.",
    "The clitoris.",
    "The Dance of the Sugar Plum Fairy.",
    "The Donald Trump Seal of Approval™.",
    "The drama club.",
    "The economy.",
    "The Fanta® girls.",
    "The folly of man.",
    "The forbidden fruit.",
    "The Force.",
    "The four arms of Vishnu.",
    "The gays.",
    "The glass ceiling.",
    "The Gulags.",
    "The Hamburglar.",
    "The hardworking Mexican.",
    "The harsh light of day.",
    "The heart of a child.",
    "The hiccups.",
    "The Holy Bible.",
    "The homosexual agenda.",
    "The Hustle.",
    "The inevitable heat death of the universe.",
    "The invisible hand.",
    "The Jews.",
    "The KKK.",
    "The Kool-aid man.",
    "The Little Engine That Could.",
    "The Make-A-Wish® Foundation.",
    "The milk man.",
    "The miracle of childbirth.",
    "The placenta.",
    "The plot of a Michael Bay movie.",
    "The Pope.",
    "The profoundly handicapped.",
    "The Rapture.",
    "The Rev. Dr. Martin Luther King, Jr.",
    "The shambling corpse of Larry King.",
    "The South.",
    "The Superdome.",
    "The taint; the grundle; the fleshy fun-bridge.",
    "The Tempur-Pedic® Swedish Sleep System™.",
    "The terrorists.",
    "The Thong Song.",
    "The Three-Fifths Compromise.",
    "The token minority.",
    "The Trail of Tears.",
    "The true meaning of Christmas.",
    "The Übermensch.",
    "The Underground Railroad.",
    "The violation of our most basic human rights.",
    "The Virginia Tech Massacre.",
    "The World of Warcraft.",
    "Third base.",
    "This answer is post-modern.",
    "Those times when you get sand in your vagina.",
    "Tickle Me Elmo™.",
    "Tiger Woods.",
    "Tom Cruise.",
    "Toni Morrison's vagina.",
    "Too much hair gel.",
    "Tripping balls.",
    "&quot;Tweeting&quot;.",
    "Twinkies®.",
    "Two midgets shitting into a bucket.",
    "Unfathomable stupidity.",
    "Uppercuts.",
    "Vehicular manslaughter.",
    "Viagra®.",
    "Vigilante justice.",
    "Vigorous jazz hands.",
    "Vikings.",
    "Waiting 'til marriage.",
    "Waking up half-naked in a Denny's parking lot.",
    "Waterboarding.",
    "Wearing underwear inside-out to avoid doing laundry.",
    "When you fart and a little bit comes out.",
    "Whipping it out.",
    "White people.",
    "White privilege.",
    "Wifely duties.",
    "Will Smith.",
    "William Shatner.",
    "Winking at old people.",
    "Wiping her butt.",
    "Women in yogurt commercials.",
    "Women's suffrage.",
    "Words, words, words.",
    "World peace.",
    "Yeast.",
    "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
    "Zeus's sexual appetites.",
    "A soulful rendition of &quot;Ol' Man River &quot;.",
    "Intimacy problems.",
    "A sweaty, panting leather daddy.",
    "Spring break!",
    "Being awesome at sex.",
    "Dining with cardboard cutouts of the cast of &quot;Friends&quot;.",
    "Another shot of morphine.",
    "Bullshit.",
    "The Google.",
    "Pretty Pretty Princess Dress-Up Board Game®.",
    "The new Radiohead album.",
    "An army of skeletons.",
    "A man in yoga pants with a ponytail and feather earrings.",
    "Mild autism.",
    "Nunchuck moves.",
    "Whipping a disobedient slave.",
    "An ether-soaked rag.",
    "A sweet spaceship.",
    "A 55-gallon drum of lube.",
    "Special musical guest, Cher.",
    "The human body.",
    "Boris the Soviet Love Hammer.",
    "The grey nutrient broth that sustains Mitt Romney.",
    "Tiny nipples.",
    "Power.",
    "Oncoming traffic.",
    "A dollop of sour cream.",
    "A slightly shittier parallel universe.",
    "My first kill.",
    "Graphic violence, adult language, and some sexual content.",
    "Fetal alcohol syndrome.",
    "The day the birds attacked.",
    "One Ring to rule them all.",
    "Grandpa's ashes.",
    "Basic human decency.",
    "A Burmese tiger pit.",
    "Death by Steven Seagal.",
    "A bigger, blacker dick.",
    "The mere concept of Applebee's®.",
    "A sad fat dragon with no friends.",
    "Catastrophic urethral trauma.",
    "Hillary Clinton's death stare.",
    "Existing.",
    "A piñata full of scorpions.",
    "Mooing.",
    "Swiftly achieving orgasm.",
    "Daddy's belt.",
    "Double penetration.",
    "Weapons-grade plutonium.",
    "Some really fucked-up shit.",
    "Subduing a grizzly bear and making her your wife.",
    "Rising from the grave.",
    "The mixing of the races.",
    "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
    "Scrotal frostbite.",
    "All of this blood.",
    "Loki, the trickster god.",
    "Whining like a little bitch.",
    "Pumping out a baby every nine months.",
    "Tongue.",
    "Finding Waldo.",
    "Upgrading homeless people to mobile hotspots.",
    "Wearing an octopus for a hat.",
    "An unhinged ferris wheel rolling toward the sea.",
    "Living in a trashcan.",
    "The corporations.",
    "A magic hippie love cloud.",
    "Fuck Mountain.",
    "Survivor's guilt.",
    "Me.",
    "Getting hilariously gang-banged by the Blue Man Group.",
    "Jeff Goldblum.",
    "Making a friend.",
    "Beefin' over turf.",
    "A squadron of moles wearing aviator goggles."];

var ANSWER_CARDS;
ANSWER_CARDS = ["40 acres and a mule.",
    "6 Fast 6 Furious.",
    "8 Mile.",
    "A bathtub of moonshine.",
    "A bidet.",
    "A bitch parade.",
    "A blind date.",
    "A bowl of dicks.",
    "A burning bush.",
    "A Burqini.",
    "A casting couch.",
    "A chai wallah.",
    "A cookie.",
    "A deal with the devil.",
    "A declining libido.",
    "A deviated septum.",
    "A dick in a box.",
    "A disappointing cereal box prize.",
    "A dog with rabies.",
    "A face tat.",
    "A failure to communicate.",
    "A Fleshlight.",
    "A forced abortion.",
    "A fruitcake.",
    "A fugue state.",
    "A gang bang.",
    "A giant sucking sound.",
    "A gimp suit.",
    "A good spanking.",
    "A guilt trip.",
    "A hemorrhoid.",
    "A hooker with a heart of gold.",
    "A hostile gay takeover.",
    "A human centipede.",
    "A Jewish American Princess.",
    "A Jihobbyist.",
    "A jive turkey.",
    "A jizzmop.",
    "A Kafkaesque wet dream.",
    "A leaky car battery.",
    "A love swing.",
    "A Magic Negro.",
    "A magic school bus.",
    "A Manwich.",
    "A monument to all my sins.",
    "A movie starring Eddie Murphy and Eddie Murphy.",
    "A one-night stand.",
    "A pap smear.",
    "A paradigm shift.",
    "A park with too much battery.",
    "A pickle.",
    "A pissing contest.",
    "A poetry slam.",
    "A polygamist ranch.",
    "A pound of flesh.",
    "A Prince Albert.",
    "A quarterlife crisis.",
    "A random act of kindness.",
    "A self-hating Jew.",
    "A Shamrock Shake.",
    "A stool sample.",
    "A stripper named Desire.",
    "A sugar daddy.",
    "A sugar rush.",
    "A Tiger Mother.",
    "A toothless gold prospector.",
    "A Toyota Hilux full of Kalashnikovs.",
    "A transvaginal ultrasound.",
    "A trip sitter.",
    "A United States Senate Page.",
    "A urinal cake.",
    "A warm gun.",
    "A wet nurse.",
    "A wide stance.",
    "Abortion doping.",
    "Abu Ghraib prison.",
    "Abused animals.",
    "Academic integrity.",
    "Acupuncture.",
    "Adult-onset diabetes.",
    "Adult ADHD.",
    "Adult circumcision.",
    "Agent Orange.",
    "&quot;Air quotes&quot;.",
    "Alcoholics Anonymous.",
    "An Easy-Bake Ultimate Oven.",
    "An emergency tracheotomy.",
    "An Imperial Wizard.",
    "An indoor voice.",
    "An ineffective coping mechanism.",
    "An infected hickey.",
    "An inferiority complex.",
    "An inflatable castle.",
    "An LGBTQQ safe space.",
    "An offer you can't refuse.",
    "An oral fixation.",
    "An udder.",
    "An un-birthday party.",
    "Anal retention.",
    "Anthrax.",
    "Anything that moves.",
    "Apartheid.",
    "Appalachian meth labs.",
    "Arabs without oil money.",
    "Arranged marriages.",
    "Artificial insemination.",
    "Asbestos.",
    "Asexuality.",
    "Asians who don't know Kung Fu.",
    "Asians with huge dicks.",
    "Asparagus-enhanced urine.",
    "Ass and titties.",
    "Ass-to-ass.",
    "Au jus.",
    "Autoerotic asphyxiation.",
    "Autofellatio.",
    "Baby fat.",
    "Baby powder.",
    "Baconators.",
    "Bad blood.",
    "Bagel Bites.",
    "Bagels and lox.",
    "Bambi.",
    "Barbed wire.",
    "Bath salts.",
    "BDSM.",
    "Beans and cornbread.",
    "Bearforce 1.",
    "Bears, the animal kind.",
    "Bears, the gay kind.",
    "Beefcake.",
    "Being a born-again virgin.",
    "Being a bottom.",
    "Being a gringo.",
    "Being a virgin, technically.",
    "Being depantsed.",
    "Being entry-level.",
    "Being framed as gay.",
    "Being gay-for-pay.",
    "Being ghetto fabulous.",
    "Being lamestream.",
    "Being pretentious.",
    "Being really flexible.",
    "Being sent to a pray-the-gay-away camp.",
    "Being tarred and feathered.",
    "Being the little spoon.",
    "Being tickled by a bushy mustache.",
    "Being well-endowed.",
    "Beluga caviar.",
    "Bible study.",
    "Bifidus Regularis.",
    "Bimbo eruptions.",
    "Bipartisanship.",
    "Birth control sabotage.",
    "Birthright Israel.",
    "Black Entertainment Television.",
    "Black rage.",
    "Blackface minstrel troupes.",
    "Blacks who aren't good at sports.",
    "Blacks with blonde hair.",
    "Blacks with tiny dicks.",
    "Blaxploitation.",
    "Blipsters.",
    "Blood diamonds.",
    "Blood sport.",
    "Blood, toil, tears and sweat.",
    "Blueballing.",
    "Bong Hits 4 Jesus.",
    "Borscht.",
    "Botulism.",
    "Brazilian waxing.",
    "Brotherly love.",
    "Brownie points.",
    "Buffalo chips.",
    "Bunga bunga.",
    "Burning Man.",
    "Buying a boyfriend experience.",
    "Buying a girlfriend experience.",
    "Buying illegal drugs off the Internet.",
    "C-SPAN 2.",
    "Caffeine-Free Diet Coke.",
    "Calculus.",
    "Camel toes.",
    "Car mechanics.",
    "Cash 4 Gold.",
    "Castration anxiety.",
    "Casual sex.",
    "Cavities.",
    "Centrifugal bumblepuppy.",
    "Chafing.",
    "Chastity.",
    "Chernobyl.",
    "Chicken and waffles.",
    "Child labor.",
    "Children of thalidomide.",
    "Children of the plantation.",
    "Chitty Chitty Gang Bang.",
    "Cirque du Soleil.",
    "Cleavage.",
    "Club sauce.",
    "Cluster munitions.",
    "Coffee capable of rendering 3rd degree burns.",
    "Coitus Interruptus.",
    "Collateralized Debt Obligations.",
    "Compression shorts.",
    "Condom fatigue.",
    "Condoms on bananas.",
    "Conjunction Junction.",
    "Conspicuous consumption.",
    "Consummation.",
    "Contemplating your navel.",
    "Coprophilia.",
    "Corporate personhood.",
    "Corrective rape.",
    "Cosplay.",
    "Cougars.",
    "Covert racism.",
    "Crab people.",
    "Criminal transmission of HIV.",
    "Crowdsourcing.",
    "Cunnilingus.",
    "Current black U.S. Senators.",
    "Curtsying.",
    "Cyberbullying.",
    "Cyberstalking.",
    "Daggering.",
    "Dead White European Males.",
    "Death panels.",
    "Debilitating withdrawal symptoms.",
    "Deep Throat.",
    "Deepwater Horizon.",
    "Depend Adult Undergarment.",
    "Dingleberries.",
    "Divorce Court.",
    "Doggystyle.",
    "Doing hoodrat stuff with your friends.",
    "Doritos Locos Tacos.",
    "Doublethink.",
    "Dressage.",
    "Drinking responsibly.",
    "Dry humping.",
    "East St. Louis.",
    "Eating sushi off a nude Japanese woman.",
    "Ebonics.",
    "Ebony &amp; Ivory.",
    "Elbow grease.",
    "Empty promises.",
    "Enron.",
    "Entrapment.",
    "Esperanto.",
    "Etsy.",
    "Eunuchs.",
    "Euthanasia.",
    "Existential dread.",
    "Faking it.",
    "False modesty.",
    "Fantasy football.",
    "Farm animals.",
    "Fava beans and a nice Chianti.",
    "Faygo.",
    "Feeding tubes.",
    "Feet.",
    "Fertilizer runoff.",
    "Fifty Shades of Grey.",
    "Fizzy Lifting Drink.",
    "Flamethrowers.",
    "Flaming Hot Cheetos.",
    "Flavor crystals.",
    "Fluffernutters.",
    "Foie gras.",
    "Foolish virgins.",
    "Foot-binding.",
    "Football concussions.",
    "Foreign exchange students.",
    "Foxconn.",
    "Fracking.",
    "Freemasonry.",
    "French maids.",
    "Frotting.",
    "Fuck-me heels.",
    "Fucking like bonobos.",
    "Fucking magnets.",
    "Gastrosexuality.",
    "Gay Fuel.",
    "Gay recruitment.",
    "Gaydar.",
    "Gayn_ggers from Outer Space.",
    "Gayngst.",
    "Gazpacho.",
    "Geishas.",
    "Gender reassignment surgery.",
    "Genital Retraction Syndrome.",
    "Genocides I've never heard of.",
    "Gentrification.",
    "George of the Jungle.",
    "Gerrymandering.",
    "Getting sauce on the side.",
    "Gigli.",
    "Gingers.",
    "Girl Scouts.",
    "Girls who eat their feelings.",
    "Girth.",
    "Giving up.",
    "Global jihad.",
    "Global Orgasm.",
    "Glow-in-the-dark condoms.",
    "Going H.A.M.",
    "Going rogue.",
    "Going Super Saiyan.",
    "Goldfish swallowing.",
    "Goldman Sachs.",
    "Good intentions.",
    "Grabbing some afternoon delight.",
    "Graduating and getting a job that doesn't require a college degree.",
    "Grannies at slot machines.",
    "Grape drink.",
    "Grape-Nuts.",
    "Greed.",
    "Grendel's grundle.",
    "Grillz.",
    "Grindr.",
    "Groupon.",
    "Growing a watermelon in one's stomach.",
    "Gruel.",
    "Guantánamo Bay.",
    "Guillotines.",
    "Gun shows.",
    "Gym teachers.",
    "Halal foods.",
    "Halliburton.",
    "Hamas.",
    "Hamburger University.",
    "Hatefucking.",
    "Having two moms.",
    "Headgear.",
    "HeadOn.",
    "Heads, shoulders, knees, and toes.",
    "Hedonists.",
    "Hegemony.",
    "Helicopter parents.",
    "Heroin chic.",
    "High-frequency trading.",
    "Hiking the Appalachian Trail.",
    "Hillel.",
    "Hindsight.",
    "Hitler Youth.",
    "Hoarding.",
    "Holding your own boobs.",
    "Holy water.",
    "Home Depot.",
    "Homeopathic remedies.",
    "Honkies doing high-end honky ass things.",
    "Honkydom.",
    "Hookworms.",
    "Hors d'oeuvres.",
    "Horticulture.",
    "Hot yoga.",
    "Housewives who are desperate.",
    "Hugs and kisses.",
    "Ice Cube.",
    "Ice cubes.",
    "Iced Tea.",
    "Illiteracy.",
    "Imaginary friends.",
    "Immaculate Conception.",
    "Indentured servitude.",
    "Indian surrogate mothers.",
    "Inescapable poverty.",
    "Infallibility.",
    "Insane Clown Posse.",
    "Institutionalized injustice.",
    "Interior Semiotics.",
    "Invisible Children.",
    "Involuntary celibacy.",
    "J Street.",
    "Jacking off at your daughter's dance recital.",
    "Jailbait.",
    "Janjaweed.",
    "Japanese super-toilets.",
    "Japanese-American internment camps.",
    "Jaundice.",
    "Jeggings.",
    "Jingoism.",
    "Job creators.",
    "Jogger's nipple.",
    "Joining the Mile High Club.",
    "Jorts.",
    "Joseph and the Amazing Technicolor Dreamcoat.",
    "Judaic Studies departments.",
    "Judging a blowjob competition.",
    "Juggalos.",
    "Jumping out of a cake.",
    "Jumping through hoops.",
    "K-pop.",
    "Kabbalism.",
    "Kangaroo Jack.",
    "Kids for cash.",
    "Kinderwhore.",
    "King Tut's penis.",
    "Klu Klux Klan robes.",
    "Kosher foods.",
    "Kraft Singles.",
    "Landslides.",
    "Lap dances.",
    "Las Vegas.",
    "Last stopping.",
    "Latex gloves.",
    "Law school.",
    "Laxatives.",
    "Lean finely textured beef.",
    "Legitimate rape.",
    "Leisurely walks.",
    "Letting the terrorists win.",
    "Libertarians.",
    "Lingerie Football League.",
    "Liposuction.",
    "Little Boy and Fat Man.",
    "Little Women.",
    "Locker rooms.",
    "Lolita, light of my life, fire of my loins.",
    "Los Zetas.",
    "LSD.",
    "Malaise.",
    "Malnutrition.",
    "Mama grizzlies.",
    "Manic Pixie Dream Girls.",
    "Manischewitz.",
    "Manscaping.",
    "Masqueraded naked parties.",
    "Massive copyright infringement.",
    "Materialism.",
    "Matzah.",
    "Mead.",
    "Meals On Wheels.",
    "Meat curtains.",
    "Meat Spin.",
    "Mecca.",
    "Medicare.",
    "Men who have sex with men.",
    "Men who sit down to pee.",
    "Men who wear bras.",
    "Menopause.",
    "Metrosexuals.",
    "Mexicans who immigrated legally.",
    "Micromanagement.",
    "Midriff.",
    "Migrant farmers.",
    "MILFs.",
    "Molly.",
    "Mom jeans.",
    "Monsanto.",
    "Montezuma's revenge.",
    "Mood rings.",
    "Moose knuckles.",
    "Mormon underwear.",
    "Mothers Against Drunk Driving.",
    "Motorboating.",
    "Muffin tops.",
    "Munchma Quchi.",
    "Mutiny.",
    "My concubine.",
    "My first time.",
    "My former lovers.",
    "My kind of people.",
    "My Little Pony: Friendship is Magic.",
    "My o-face.",
    "Naked lunch.",
    "Name-dropping.",
    "Narcissism.",
    "NASCAR dads.",
    "National Public Radio.",
    "Native American casinos.",
    "Native American mascots.",
    "Negotiating with terrorists.",
    "Nihilists.",
    "Nostalgia.",
    "Oatmeal laced with radioactive isotopes.",
    "Object Rape.",
    "Oiled massages.",
    "One-way mirrors.",
    "OPEC.",
    "Oral tradition.",
    "Organ harvesting.",
    "Overfishing.",
    "OxiClean.",
    "Pandering to female voters.",
    "Party poopers.",
    "Pasties.",
    "Peeing on it.",
    "Peer pressure.",
    "Pegging.",
    "Penis fencing.",
    "Pepper spray.",
    "Pheromones.",
    "Phlegm.",
    "Pink eye.",
    "Pinterest.",
    "Pity.",
    "Placebos.",
    "Planned obsolescence.",
    "Planned Parenthood.",
    "Playing doctor.",
    "Plus-size models.",
    "Pool boys.",
    "Poops that sink.",
    "Poppycock.",
    "Pork bellies.",
    "Pornographic connect-the-dots books.",
    "Port-a-potties.",
    "Postal workers.",
    "Postpartum depression.",
    "Power ballads.",
    "Power tools.",
    "Praying for your period.",
    "Predator drones.",
    "Pregnancy sex.",
    "Pretending to be a prophet.",
    "Prison showers.",
    "Private browsing.",
    "Product placement. . . Pepsi.",
    "Protest sex.",
    "Puppy mills.",
    "Purity balls.",
    "Pussy Riot.",
    "Putting a ring on it.",
    "Putting your enemies into a woodchipper.",
    "Pygmies.",
    "Quality father-son bonding time.",
    "Racial profiling.",
    "Racial quotas.",
    "Raging hormones.",
    "Rainbow toe socks.",
    "Reaganomics.",
    "Receding hairlines.",
    "Recidivism.",
    "Reconstruction.",
    "Redlining.",
    "Refugees.",
    "Remembering the Titans.",
    "Reparations.",
    "Restless Leg Syndrome.",
    "Reverse cowgirl.",
    "Ricochet.",
    "Righteous indignation.",
    "Roadkill.",
    "Romeo and Juliet laws.",
    "Rubbing Budai's belly.",
    "Ruff Riders.",
    "Running amok.",
    "Rust.",
    "S'mores.",
    "Sad clowns.",
    "Sagging.",
    "Sailor Moon.",
    "Santorum.",
    "Saying Latino with a Latino accent.",
    "Schadenfreude.",
    "Scissoring.",
    "Seabiscuit.",
    "Seasonal affective disorder.",
    "Segregated proms.",
    "Self-actualization.",
    "Sensory deprivation.",
    "Seven layer dip.",
    "Seventeen Magazine.",
    "Sex dice.",
    "Sex-selective abortions.",
    "Sexual cannibalism.",
    "Sexual capital.",
    "Sexual onomatopoeia.",
    "Sexually active band geeks.",
    "Sexy PETA PSAs.",
    "Shabbos.",
    "Sharia law.",
    "Shark Week.",
    "Shirking.",
    "Shit creek.",
    "Shock and Awe.",
    "Short shorts.",
    "Shrooms.",
    "Slacktivism.",
    "SlapChop.",
    "Sleep sex.",
    "Slender mannequins.",
    "Slut-shaming.",
    "Slutwave.",
    "Smells that trigger my worst memories.",
    "Snitches.",
    "Snorting wasabi.",
    "Snuggies.",
    "Soccer moms.",
    "Social Security.",
    "Solidarity.",
    "Somali pirates.",
    "Something rotten.",
    "Spanx.",
    "Spermicide.",
    "Sploosh.",
    "Sporadic Fatal Insomnia.",
    "Spotted dick.",
    "Spray tans.",
    "Stabbing through a curtain.",
    "Starting a coke habit.",
    "Starving Africans.",
    "Stockholm syndrome.",
    "Stoning.",
    "Stop and frisk.",
    "Student-teacher love affairs.",
    "Study drugs.",
    "Subprime mortgages.",
    "Suicide by cop.",
    "Superbabies.",
    "Swag.",
    "Swingers.",
    "Sympathizing with terrorists.",
    "Synergy.",
    "Tae Bo.",
    "Taking Ambien and trying to stay awake.",
    "Taping your thumbs to your hands and pretending to be a dinosaur.",
    "Tasers.",
    "Teabagging.",
    "Teach For America.",
    "Teenyboppers.",
    "Teledildonics.",
    "Telemundo.",
    "The ACLU.",
    "The Adventures of Pluto Nash.",
    "The aristocrats!",
    "The Back-to-Africa movement.",
    "The bargain bin.",
    "The Bermuda Triangle.",
    "The bi-curious.",
    "The Birth of a Nation.",
    "The Black Death.",
    "The Black Panthers.",
    "The blogosphere.",
    "The Book of Mormon.",
    "The Boy Scouts of America.",
    "The Brave Little Toaster.",
    "The Cha Cha Slide.",
    "The Challenger Explosion.",
    "The Chosen People.",
    "The cinnamon challenge.",
    "The circle of life.",
    "The Color Purple.",
    "The Communist Manifesto.",
    "The cool, refreshing taste of Bud Light Lime.",
    "The cult of domesticity.",
    "The Electoral College.",
    "The Exxon Valdez oil spill.",
    "The fat kid eating chocolate cake in Matilda.",
    "The Federal Reserve.",
    "The Final Solution.",
    "The Flying Nun.",
    "The Ford Pinto.",
    "The fraternal birth order effect.",
    "The Fugly Duckling.",
    "The G-Spot.",
    "The Gay Science.",
    "The Giving Tree.",
    "The Great American Challenge.",
    "The Great and Powerful Oz.",
    "The handkerchief code.",
    "The Happy Hands Club.",
    "The help of a sassy gay friend.",
    "The Hindenburg.",
    "The human papillomavirus.",
    "The Illuminati.",
    "The Inquisition.",
    "The international situation.",
    "The Invisible Man.",
    "The IRS.",
    "The Isle of Lesbos.",
    "The Jonestown massacre.",
    "The Khmer Rouge.",
    "The Kosher Nostra.",
    "The Land Before Time.",
    "The Last Mohican.",
    "The Lollipop Guild.",
    "The Lorax.",
    "The lost tribe of Israel.",
    "The Macarena.",
    "The Man.",
    "The Matzo Ball.",
    "The menarche.",
    "The Midas touch.",
    "The military-industrial complex.",
    "The model minority.",
    "The Mormon Tabernacle Choir.",
    "The most dangerous game.",
    "The murder of Kitty Genovese.",
    "The Muslim Brotherhood.",
    "The National Hobo Convention.",
    "The NRA.",
    "The occult.",
    "The one-eyed, one-horned, flying, purple people eater.",
    "The Oneida Community.",
    "The opiate of the masses.",
    "The power of friendship.",
    "The proletariat.",
    "The Protocols of the Elders of Zion.",
    "The Qur'an.",
    "The rooting reflex.",
    "The seven-year itch.",
    "The Shake Weight.",
    "The silent treatment.",
    "The Singularity.",
    "The Sisterhood of the Traveling Pants.",
    "The social contract.",
    "The status-quo.",
    "The suicide hotline.",
    "The Titanic.",
    "The Tony Awards.",
    "The Triangle Trade.",
    "The Truffle Shuffle.",
    "The underemployed.",
    "The vast right-wing conspiracy.",
    "The war on Christmas.",
    "The working poor.",
    "Theatre-in-the-round.",
    "Thinspiration.",
    "Those shoes with the toe things.",
    "Threatening to poop your pants.",
    "Time to snowball.",
    "Tittyfucking.",
    "Toddlers &amp; Tiaras.",
    "Too fat for sex.",
    "Totaling a Porsche for the insurance money.",
    "Toupées.",
    "Townies.",
    "Trapped In The Closet Chapters 1-22.",
    "Traveling lawn gnomes.",
    "Triumph of the Will.",
    "Trust-falling and not catching.",
    "Trustafarians.",
    "Truth serum.",
    "Truthiness.",
    "Tumblr.",
    "Turbans.",
    "Turkey basters.",
    "Tuskegee syphilis experiment.",
    "Twinks.",
    "Two chicks at the same time.",
    "Ugg Boots.",
    "Umami.",
    "Underbeard.",
    "Underwater basket weaving.",
    "Undifferentiated gonads.",
    "Unlimited breadsticks.",
    "Unobtainium.",
    "Unrequited love.",
    "Up against the wall.",
    "Upperdecking.",
    "Urban decay.",
    "Using all the parts of a buffalo.",
    "Using spit.",
    "Vagina Dentata.",
    "Vagina envy.",
    "Vaginal irrigation.",
    "Validating yourself through flirting.",
    "Vanity sizing.",
    "Varicose veins.",
    "Vegans.",
    "Very erotic, very violent.",
    "Vodka-soaked tampons.",
    "Vuvuzelas.",
    "Waifs.",
    "Wal-Mart.",
    "Walk-in baths.",
    "Water birth.",
    "Weapons of mass destruction.",
    "Wearing a hoodie.",
    "Weight Watchers.",
    "What the Hokey-Pokey's all about.",
    "Whips.",
    "White flight.",
    "White man's burden.",
    "White phosphorous.",
    "White-collar crime.",
    "Whore d'oeuvres.",
    "Wiggers.",
    "Wikileaks.",
    "Wikimedia erotica.",
    "Winning a tontine.",
    "Women.",
    "Women's sports.",
    "Woof.",
    "Workplace sabotage.",
    "X-ray vision.",
    "YAZ.",
    "Yellow fever.",
    "Yellowcake uranium.",
    "Yoga Moms.",
    "Yoga pants.",
    "Yuppies.",
    "Zumba.",
    "Zyklon B.",
    "27th President of the United States, Howard Taft.",
    "Abraham Lincoln, Vampire Slayer.",
    "Al Gore.",
    "Anne Frank.",
    "Archbishop Desmond Tutu.",
    "Adele.",
    "Aretha Franklin's really big hat.",
    "Aunt Jemima.",
    "Ayn Rand.",
    "Baby Jessica.",
    "Balto.",
    "Barack Obama's Kenyan father.",
    "Barbra Streisand.",
    "Ben Bernanke.",
    "Benjamin Franklin.",
    "Bernie Madoff.",
    "Bert &amp; Ernie.",
    "Betty White.",
    "Big Bird.",
    "Bill Clinton.",
    "Bill Cosby.",
    "Bill Gates.",
    "Bill O'Reilly.",
    "Björk.",
    "Bobby Fischer.",
    "Bobby Flay.",
    "Bobby Jindal.",
    "Boo Radley.",
    "Bristol Palin.",
    "Carrot Top.",
    "Charles Manson.",
    "Charlie Sheen.",
    "Cho Chang.",
    "Clint Eastwood.",
    "Condoleezza Rice.",
    "Cornel West.",
    "Crispus Attucks.",
    "Dennis Rodman.",
    "Donald Rumsfeld.",
    "Donald Trump.",
    "Dora The Explorer.",
    "Doris Kearns Goodwin.",
    "Dr. Kevorkian.",
    "Dred Scott.",
    "Elián González.",
    "Eliot Spitzer.",
    "Emma Watson.",
    "Enya.",
    "Eva Braun.",
    "Fidel Castro.",
    "Frederick Douglass.",
    "Garrison Keillor.",
    "Genie, the feral child.",
    "George Washington Carver.",
    "Georgia O'Keeffe.",
    "Geraldo Rivera.",
    "Gérard Depardieu.",
    "Harriet Tubman.",
    "Herman Cain.",
    "Hillary Rodham Clinton.",
    "Ho Chi Minh.",
    "Hu Jintao.",
    "Hugh Hefner.",
    "Ice-T.",
    "Ira Glass.",
    "Jefferson Davis.",
    "Our Lord and Savior, Jesus Christ.",
    "Jodie Foster, child prostitute.",
    "Joe 6-pack.",
    "Joe Biden.",
    "John McCain.",
    "John Yoo.",
    "Joseph Goebbels.",
    "Joseph Kony.",
    "Joseph McCarthy.",
    "Judas.",
    "Julian Assange.",
    "Karl Rove.",
    "Kate Middleton.",
    "Katy Perry shooting whipped cream out of her breasts.",
    "Khalid Sheikh Mohammed.",
    "Lady Gaga's meat dress.",
    "L. Ron Hubbard.",
    "Larry Craig.",
    "Leeroy Jenkins.",
    "Lil' Jon &amp; The Eastside Boyz.",
    "Lindsay Lohan.",
    "Lonesome George.",
    "Macaulay Culkin.",
    "Madonna.",
    "Mahmoud Ahmadinejad.",
    "Malcolm X.",
    "Mark Foley.",
    "Mark Zuckerberg.",
    "Matt Damon.",
    "Maya Angelou.",
    "Mel Gibson.",
    "Michael Cera.",
    "Michael Moore.",
    "Michael Phelps.",
    "Mike Tyson.",
    "Miley Cyrus.",
    "Mitt Romney.",
    "Monica Lewinsky.",
    "Mother Theresa.",
    "Napoleon Bonaparte.",
    "Neil DeGrasse Tyson.",
    "Nelson Mandela.",
    "Newt Gingrich.",
    "O.J. Simpson.",
    "Octomom.",
    "Oprah Winfrey.",
    "Osama Bin Laden.",
    "Paul Krugman.",
    "Pocahontas.",
    "Pol Pot.",
    "Pontius Pilate.",
    "Posh Spice.",
    "Raffi.",
    "Rainbow Stalin.",
    "Ralph Nader.",
    "Reverend Al Sharpton.",
    "Richard Branson.",
    "Robert Mugabe.",
    "Rodney King.",
    "Roman Polanski.",
    "RON PAUL 2012!!!",
    "Rosa Parks.",
    "Rudy Giuliani.",
    "Rupert Murdoch.",
    "Rush Limbaugh.",
    "Ryan Seacrest.",
    "Saddam Hussein.",
    "Sally Hemmings.",
    "Salman Rushdie.",
    "Sasha and Malia Obama.",
    "Smurfette.",
    "Socialist Helen Keller.",
    "The Rev. Sir Dr. Stephen T. Mos Def Colbert, D.F.A., Heavyweight Champion of the World**.",
    "Steve Jobs.",
    "Sully Sullenberger, III.",
    "Suri Cruise.",
    "Tebowing.",
    "Ted Haggard.",
    "The Elephant Man.",
    "The Jonas Brothers.",
    "The Most Interesting Man in the World.",
    "The Olsen twins.",
    "The Winklevosses.",
    "Tigger.",
    "Tyler Perry.",
    "Tyra Banks.",
    "Village People.",
    "Vincent Van Gogh.",
    "Vladimir Putin.",
    "Whoopi Goldberg.",
    "Xena, Warrior Princess.",
    "Xenu.",
    "Zooey Deschanel."];

var QUESTION_CARDS = ["__ Ain't Nuthin' Ta F' Wit.",
        "__ Considered Harmful.",
        "__ each day keeps the doctor away.",
        "__ will be the title of my memoir.",
        "__ will set you free.",
        "__, because you're worth it.",
        "__, same time tomorrow?",
        "__: I was young and needed the money.",
        "__: Never leave home without it.",
        "__: Unsafe at any speed.",
        "__? Not in my backyard.",
        "__? Son, I am disappointed.",
        "__? The Greeks had a word for that.",
        "__. Shaken, not stirred.",
        "&quot;Plop, plop, fizz, fizz&quot; is now used to sell __.",
        "A million dollars isn't cool. You know what's cool?",
        "A newly discovered Grimm fairy tale warns children about __.",
        "A spectre is haunting Europe—-the spectre of __.",
        "A spoonful of sugar helps __ go down.",
        "Ah, __. We meet at last.",
        "All I want for Christmas is __.",
        "All right, Mr. DeMille, I'm ready for __.",
        "All Virginia Woolf ever wanted was a room of __.",
        "Animal rights activists object to the testing of __ on animals.",
        "Aragorn: You have my sword. Legolas: And you have my bow. Gimli: And __.",
        "Are you coming to the church event this weekend? __ for Jesus?",
        "Are you there, God? It's me, __.",
        "Ask not what __ can do for you; ask what you can do for __.",
        "At the final stroke of midnight, Cinderella turned into __.",
        "Barack Obama insisted that Camp David have a steady supply of __.",
        "Be not afraid of __: some are born __, some achieve __, and some have __ thrust upon them.",
        "Brother, can you spare __?",
        "But wait, there's more. Call in next ten minutes to receive __.",
        "Carpe __. Seize __, boys. Make your lives extraordinary.",
        "Coachella will feature Dr. Dre performing with a hologram version of __.",
        "Delivered in 30 minutes or the next one's __.",
        "Don't hate me because I'm __.",
        "Don't miss the hot __-on-__ action.",
        "Errol Morris's next documentary is a nuanced reflection on __.",
        "Fie, foh, and fum, I smell the blood of __.",
        "Fourscore and seven years ago our fathers brought forth on this continent __.",
        "Frankly, my dear, I don't give __.",
        "Friends, Romans, countrymen, lend me __.",
        "Getting there is half the fun. The other half is __.",
        "Grandmother, what __ you have!",
        "Guess who's coming to dinner.",
        "Has anyone seen my voodoo doll of __?",
        "Have __, will travel.",
        "Have you heard the new club track, &quot;Get Your __ On&quot;?",
        "He who lives by __ shall die by __.",
        "Hey, I read your OkCupid profile and noticed our mutual interest in __.",
        "Historians agree; 2012 was the dawn of the post-__ society.",
        "Hitler had some good ideas, too, you know. Like __.",
        "Honey, I shrunk __.",
        "How can we ever repay you?",
        "How did I get my 15 minutes of fame?",
        "How did I lose all that weight?",
        "How do I reach these kids?",
        "I had a lover's quarrel with __.",
        "I hate this new Facebook feature for __.",
        "I have always depended on the kindness of __.",
        "I know __ like the back of my hand.",
        "I know it looks bad, but if we get through this, you can have __.",
        "I like __, and I cannot lie.",
        "I lost the scavenger hunt because I couldn't find __.",
        "I love the smell of __ in the morning.",
        "I was lucky to find an unpaid internship for __.",
        "I, for one, welcome our __ overlords.",
        "I'm a family man. I run a family business. This is my son and my partner, __.",
        "I'm like Johnny Appleseed but with fewer apples and more __.",
        "I'm a doctor, not __.",
        "I'm at the combination Pizza Hut &amp; __.",
        "I'm cursed. Everything I touch turns into __.",
        "I'm not __, but I play one on TV.",
        "I'm so lucky that my health insurance covers __.",
        "I'm writing a self-help book titled &quot;Lessons From__&quot;.",
        "If __ is wrong, I don't want to be right.",
        "If you'll excuse me, I have a rendez-vous with __.",
        "If you're looking for fun, New York's hottest club is __.",
        "In a 5-4 ruling, the Supreme Court upheld the constitutionality of __.",
        "In all likelihood, our next president will resign over __-gate.",
        "In Aronofsky's Requiem for a Dream, three friends struggle to overcome their addiction to __.",
        "In fashion, one day you're in, and the next day you're __.",
        "In my favorite Japanese game show, contestants wrestle with __.",
        "In my lucid dreams, I take control of __.",
        "In my near-death experience, images of __ flashed before my eyes.",
        "Investing in __ was terrible for my stock portfolio.",
        "Isaiah 6:5: Then said I, Woe is me! for I am __.",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of __.",
        "It's tragic that high schools across America are cutting funding for __.",
        "Justin Timberlake is bringing __ back.",
        "Keep calm and __.",
        "Keep your friends close, but __ closer.",
        "Ladies and Gentlemen of the jury, allow me to present exhibit A, __. I rest my case.",
        "LGBTQQ now accepts people who love __.",
        "Lindsay Lohan is serving time for driving under the influence of __.",
        "Listen, __. We have to stop meeting like this. My wife's getting suspicious.",
        "Listen, doctor. I have this friend who's been experimenting with __. Should he stop?",
        "Listen, my children, and you shall hear of the midnight ride of __.",
        "Mama always said life was like a box of __.",
        "Marco Polo took the Silk Road to China, and returned on __ Road.",
        "Market researchers are using focus groups to investigate consumer interest in __.",
        "Mom, Dad, I've decided to pursue a career in __.",
        "Mom, I'll be out in a second! I'm just finishing up with __.",
        "Moses climbed Mount Sinai to receive __ from God.",
        "MTV's new makeover show is Pimp __.",
        "My definition of hooking-up includes __.",
        "My doppelgänger is like me but with a proclivity for __.",
        "My favorite Korean restaurant pickles __.",
        "My favorite rom-com is When Harry Met __...",
        "My horoscope said to beware __.",
        "My new favorite musical genre is __-core.",
        "My New Year's resolution includes __.",
        "My psychiatrist says I have an irrational fear of __.",
        "My self-portrait is made entirely of __.",
        "Nancy Drew: The Clue In __.",
        "Never bring __ to a gunfight.",
        "New at McDonald's: The Mc__.",
        "Next on the History Channel, the Rise and Fall of __.",
        "No amount of practice or prayer could have prepared The Jonas Brothers for the struggles of __.",
        "None of the children expected the Piñata to be filled with __.",
        "Now listen, pardner, __ ain't big enough for the both of us.",
        "O __! What crimes are committed in thy name!",
        "On the first day of Christmas, my true love gave to me __.",
        "Once upon a time, there lived a princess who longed for __.",
        "One morning, as Gregor Samsa was waking up from anxious dreams, he discovered that in his bed he had been changed into __.",
        "One of Stanley Kubrick's unrealized projects was an epic biopic of __.",
        "One of Woody Allen's earliest films features an ambiguously Jewish man falling in love with __.",
        "Please welcome our guest of the evening, The Talented Mr. __.",
        "Pledge now, and your NPR commemorative tote bag will include __.",
        "Police found traces of blood and alcohol, as well as __ at the scene of the crime.",
        "Rumor has it, __ can be a great aphrodisiac.",
        "Scholars have only recently begun to study the Ancient Greek God of __.",
        "School administrators believe gel bracelets indicate that students are engaged in __.",
        "Scientists say we can solve the energy crisis by harnessing the power of __.",
        "Screw this contract. I didn't sign up for __.",
        "Shall I compare thee to __?",
        "So long, and thanks for __.",
        "Spare __ and spoil the child.",
        "Speak softly, and carry __.",
        "Steve Jobs' unfinished dream was to reinvent __.",
        "Sticks and stones may break my bones, but __ can never hurt me.",
        "Straight outta Compton, crazy motherfucker named __.",
        "That's not __; this is __.",
        "The 10th circle of hell is reserved for __.",
        "The 28th Amendment to the U.S. Constitution prohibits government involvement in __.",
        "The Blue Man Group has found a way to make music out of __.",
        "The chief business of the American people is __.",
        "The city council has set up a town-hall meeting where residents can voice their opinion on __.",
        "The city streets are closed due to the parade for __.",
        "The electric chair was inhumane and uncivilized. Now we use __.",
        "The Epcot exhibit for the Netherlands features __.",
        "The FBI has declassified a report titled __: Friend or Foe?",
        "The few, the proud, __.",
        "The first rule of __ is you do not talk about __.",
        "The government should balance its budget by taxing __.",
        "The Greeks were clever to fill the wooden horse with __.",
        "The Hardy Boys: The Mystery of __.",
        "The Internet's not a truck. It's a series of __.",
        "The latest edition of the DSM includes people who have difficulty with __.",
        "The only thing we have to fear is __.",
        "The road to Hell is paved with __.",
        "There are some things money can't buy. For everything else, there's __.",
        "There's a time for love, a time for hate, and a time for __.",
        "There's no crying in __.",
        "There's something you should know about me. About __.",
        "They call it a &quot;Royal with __.&quot;",
        "They can have __ when they pry it from my cold, dead hands.",
        "They don't make __ like they used to.",
        "They may take our lives, but they'll never take __.",
        "This is the dawning of the Age of __.",
        "This is your brain. This is your brain on __. Any questions?",
        "The PBS NewsHour is made possible by the Partnership For A World Without __.",
        "Three Wise Men visited Jesus after his birth, bearing three gifts: gold, frankincense, and __.",
        "To impress my friends, I became very proficient in __.",
        "Today is National __ Awareness Day.",
        "Trust me, I'm __.",
        "Two roads diverged in a wood, and I took the one with __, and that has made all the difference.",
        "Tyler Perry presents: Madea and __.",
        "Under what circumstances did Little Bo Peep find her sheep?",
        "Upton Sinclair's novel The Jungle exposed the meat packing industry's horrendous practice involving __.",
        "Walt Disney presents: __ on Ice!",
        "Yo Taylor, I'm really happy for you. I'ma let you finish, but __ had one of the best videos of all time.",
        "You want to know what comes between me and my Calvin's? __.",
        "We can't stop here! This is __ country!",
        "WE HAVE MET THE ENEMY AND HE IS __.",
        "We need to make __ safe, legal and rare.",
        "We ran a background check on you and found __. Would you mind explaining that to us?",
        "We're off to see the wizard, the wonderful wizard of __.",
        "What brings all the boys to the yard?",
        "What brings me closer to God?",
        "What can go faster than the speed of light?",
        "What deserves a television show?",
        "What did I abandon freshman year?",
        "What did I bring to show and tell as a child?",
        "What did I bring to the retirement home?",
        "What did I buy at a garage sale?",
        "What did I find in my bed after my sleepwalk?",
        "What did I get from The Giving Tree?",
        "What did I hear inside the conch?",
        "What did my dad like on Facebook?",
        "What did my father put in my dowry?",
        "What did President Obama consider &quot;a teachable moment&quot;?",
        "What did the Aztecs routinely sacrifice for Quetzalcoatl?",
        "What did the doctor order?",
        "What do the French serve à la carte?",
        "What does Mr. T pity?",
        "What does this button do?",
        "What else is fair and balanced?",
        "What ends too quickly?",
        "What fate befell the last little Injun?",
        "What gets me through the day?",
        "What helps me relax?",
        "What homemade item did I buy off Etsy?",
        "What is endearingly anthropomorphized in the next Pixar film?",
        "What is Victoria's Secret?",
        "What keeps going, and going, and going?",
        "What keeps me from getting laid?",
        "What killed the dinosaurs?",
        "What made me finally see the error of my ways?",
        "What makes me gasp for breath?",
        "What makes me homesick?",
        "What means never having to say you're sorry?",
        "What melts in your mouth, not in your hands?",
        "What shall we do with the drunken sailor?",
        "What shook me all night long?",
        "What the fuck do investment bankers do, anyway?",
        "What time is it? __ time.",
        "What was I pleased to find on Chatroulette?",
        "What was in the gift bag for this year's Academy Awards?",
        "What was my rite of passage?",
        "What will never fucking happen in my wildest dreams?",
        "What would I do for a Klondike Bar?",
        "What would make church more exciting?",
        "What zero tolerance policy got me suspended in high school?",
        "What's the new party drug?",
        "What's at the center of the universe?",
        "What's at the end of my Rube Goldberg machine?",
        "What's bigger in Texas?",
        "What's bigger than Jesus?",
        "What's finger-lickin' good?",
        "What's my family business?",
        "What's my hangover cure?",
        "What's my political party's platform?",
        "What's the most confusing?",
        "What's the most dysfunctional?",
        "What's the most inspirational?",
        "What's the most misunderstood?",
        "What's the most natural?",
        "What's the most philosophical?",
        "What's the most powerful?",
        "What's the new trend in perfumes and fragrances?",
        "What's the newest trend in headwear?",
        "What's the theme for our senior prom?",
        "When friends suggest __, just say, &quot;No.&quot;",
        "During her 1996 trip to Bosnia, Hillary Clinton had to run to a base in order to avoid __.",
        "When life gives you __, make __-ade.",
        "When my wife was pregnant, she craved __.",
        "Where we're going, we don't need __.",
        "Who are you, and what have you done with __?!",
        "Who's my secret admirer?",
        "Who's the newest member of Village People?",
        "Why can't __ be an Olympic sport?",
        "Why does the caged bird sing?",
        "Why is there a dead Pakistani on my couch?",
        "Why is this night different from all other nights?",
        "Woe, woe is me. Nobody knows __ I see.",
        "Would you still love me if I was __.",
        "Yo ho ho and a bottle of __.",
        "You don't have to be Jewish to love __.",
        "You get __! And you get __! Everybody gets __!",
        "You had me at &quot;__.&quot;",
        "You're going to Los Angeles? Don't miss __ district."];
